name: BuildingStaff
main: com.balugaq.buildingstaff.implementation.BuildingStaffPlugin
depend: [ Slimefun ]
authors: [ balugaq, wickidcow ]
website: https://github.com/wickidcow/SF_BuildingStaff
version: ${project.version}
api-version: 1.20
commands:
  buildingstaff:
    aliases: bs
    description: Building Staff base command
