name: BuildingStaff
main: com.balugaq.buildingstaff.implementation.BuildingStaffPlugin
depend: [ Slimefun ]
softdepend: [ Rebar, Pylon ]
authors: [ balugaq, wickidcow ]
website: https://github.com/wickidcow/SF_BuildingStaff
version: ${project.version}
api-version: '1.21'
commands:
  buildingstaff:
    aliases: bs
    description: Building Staff base command
